language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "8"
notifications:
  email:
    recipients:
      - aron.helser@kitware.com
    on_success: change
    on_failure: always
install:
  - npm install

script:
  - npm run build
