language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 12
notifications:
  email:
    recipients:
      - aron.helser@kitware.com
    on_success: change
    on_failure: always
install:
  - yarn

script:
  - yarn build
  - git config --global user.name "Travis CI"
  - git config --global user.email "aron.helser@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/wwayne/react-tooltip.git
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn gh-pages -- --repo ${GIT_PUBLISH_URL}; fi
  - cd example
  - yarn
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: refactoring
  
after_success:
  - yarn semantic-release
  
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
