name: Run Bundlesize

on:
  workflow_call:

jobs:
  bundlesize:
    runs-on: ubuntu-latest
    steps:
      - name: Install dev dependencies
        run: yarn build

      - name: Bundlesize
        run: yarn run bundlesize

