name: Pull request workflow

on:
  push:
    branches:
      - '!master'
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  bundlesize:
    uses: ./.github/workflows/bundlesize.yaml
