name: Pull request workflow

on:
  push:
    branches:
      - '!master'
  pull_request:

jobs:
  pull_request_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: Install dev dependencies
        run: yarn install

  lint:
    needs: pull_request_checks
    uses: ./.github/workflows/lint.yaml

  bundlesize:
    needs: pull_request_checks
    uses: ./.github/workflows/bundlesize.yaml
