name: Release workflow

on:
  push:
    branches:
      - master

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  release:
    needs: lint
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dev dependencies
        run: yarn install

      - name: Publish package using semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn build
          yarn run semantic-release
